### ISSUE TITLE
installation feedback

### ISSUE THREAD

**Issue by emicklei** [josestrk/PersonalQR#4]
Hi,

Just want to report the warning I get when installing this application. You probably want to upgrade some deps.

```
npm WARN deprecated jsonwebtoken@3.2.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
npm WARN deprecated jws@1.0.1: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN prefer global jshint@2.5.11 should be installed with -g
...
npm WARN EPEERINVALID mongoskin@1.4.13 requires a peer of mongodb@~1.4 but none was installed.
```

thank you for sharing this project code

**Comment by Alevale** [comment]
Sorry for the late answer.
@josestrk and I, have been quite busy and the notification about this project never reached me, I would like to take a look into this, and probably try to give you a solution asap (he just wrote me about this issue).

As far as i know, upgrading the project is not something trivial (if you have been through the dependency hell once you never want to go again)

Cheers and hope to be able to help in the future!

**Comment by Alevale** [comment]
Thank you for the remarks you did on the project.
I've been investigating and I have a fix that will be added in the next following days, after the approval of the others collaborators in the project.
